[2023-11-19T20:34:13.787+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim manual__2023-11-19T20:34:04.063797+00:00 [queued]>
[2023-11-19T20:34:13.792+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim manual__2023-11-19T20:34:04.063797+00:00 [queued]>
[2023-11-19T20:34:13.792+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-19T20:34:13.797+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_outcome_types_dim> on 2023-11-19 20:34:04.063797+00:00
[2023-11-19T20:34:13.801+0000] {standard_task_runner.py:57} INFO - Started process 132 to run task
[2023-11-19T20:34:13.804+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load_outcome_types_dim', 'manual__2023-11-19T20:34:04.063797+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpr6fdbn9l']
[2023-11-19T20:34:13.806+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask load_outcome_types_dim
[2023-11-19T20:34:13.858+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load_outcome_types_dim manual__2023-11-19T20:34:04.063797+00:00 [running]> on host dcd2747ca857
[2023-11-19T20:34:13.918+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load_outcome_types_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T20:34:04.063797+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-19T20:34:04.063797+00:00'
[2023-11-19T20:34:13.954+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/load.py", line 26, in load_data
    pd.read_parquet(table_file).to_sql(table_name, conn, if_exists="append", index=False, method=insert_on_conflict_nothing)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-19/processed/dim_outcome_types.parquet'
[2023-11-19T20:34:13.968+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load_outcome_types_dim, execution_date=20231119T203404, start_date=20231119T203413, end_date=20231119T203413
[2023-11-19T20:34:13.981+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 70 for task load_outcome_types_dim ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-19/processed/dim_outcome_types.parquet'; 132)
[2023-11-19T20:34:14.016+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T20:34:14.027+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
