[2023-11-25T08:31:34.103+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform manual__2023-11-25T08:31:27.502877+00:00 [queued]>
[2023-11-25T08:31:34.107+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform manual__2023-11-25T08:31:27.502877+00:00 [queued]>
[2023-11-25T08:31:34.108+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T08:31:34.113+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-25 08:31:27.502877+00:00
[2023-11-25T08:31:34.118+0000] {standard_task_runner.py:57} INFO - Started process 110 to run task
[2023-11-25T08:31:34.121+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'manual__2023-11-25T08:31:27.502877+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpagkya7op']
[2023-11-25T08:31:34.123+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask transform
[2023-11-25T08:31:34.156+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform manual__2023-11-25T08:31:27.502877+00:00 [running]> on host 345afa9fabd7
[2023-11-25T08:31:34.195+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-25T08:31:27.502877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-25T08:31:27.502877+00:00'
[2023-11-25T08:31:34.716+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date_dim['ts'] = pd.to_datetime(date_dim['ts'])

[2023-11-25T08:31:34.718+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date_dim['year'] = date_dim['ts'].apply(lambda x: int(x.year))

[2023-11-25T08:31:34.721+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date_dim['month'] = date_dim['ts'].apply(lambda x: int(x.month))

[2023-11-25T08:31:34.722+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:34: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date_dim['day'] = date_dim['ts'].apply(lambda x: int(x.day))

[2023-11-25T08:31:34.724+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:35: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date_dim['hour'] = date_dim['ts'].apply(lambda x: int(x.hour))

[2023-11-25T08:31:34.727+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date_dim['minute'] = date_dim['ts'].apply(lambda x: int(x.minute))

[2023-11-25T08:31:34.729+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:37: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date_dim['second'] = date_dim['ts'].apply(lambda x: int(x.second))

[2023-11-25T08:31:34.731+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:43: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['outcome_type'] = data['outcome_type'].apply(lambda x: str(x))

[2023-11-25T08:31:34.734+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 86, in transform_data
    outcome_fct = create_outcome_fct(data, date_df, outcome_df)
NameError: name 'date_df' is not defined
[2023-11-25T08:31:34.746+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=transform, execution_date=20231125T083127, start_date=20231125T083134, end_date=20231125T083134
[2023-11-25T08:31:34.755+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task transform (name 'date_df' is not defined; 110)
[2023-11-25T08:31:34.798+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
